version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: ./mange-pic-fudan
    volumes:
      - static:/app/static
      - media:/app/media
      - mysqlbackup:/app/backup_mysql
    restart: always
    # privileged: true

    command: ./entrypoint.sh
  nginx:
    depends_on:
      - backend
    build: ./nginx
    volumes:
      - static:/static
    restart: always
    ports:
      - 8071:80

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # image: mysql:5.6
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "operatepathology"
      MYSQL_ROOT_PASSWORD: pcl123456
    volumes:
      - db-data:/var/lib/mysql
    # command:
    #   [
    #     "mysqld",
    #     "--character-set-server=utf8mb4",
    #     "--collation-server=utf8mb4_unicode_ci",
    #     "--default-authentication-plugin=mysql_native_password",
    #   ]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

volumes:
  db-data:
  static:
  media:
  mysqlbackup:
